### ISSUE TITLE
bump repo to create release

### ISSUE THREAD

**Issue by pelikhan** [emwta/pxt-iBit#4]
Run ``pxt bump`` from the repo folder to generate a new version number and a github release.

**Comment by emwta** [comment]
You mean create new repo name is ``pxt-bump`` and release, but ``pxt-iBit`` can't add to package to makecode?

**Comment by pelikhan** [comment]
Just use the command line tool and run “pxt bump” in the terminal :)

**Comment by emwta** [comment]
Ok :) , I'm edited block names and deleted .png, block names dosen't  match with other API. I hope you'll be ok.

**Comment by pelikhan** [comment]
I don't see any release tag on this repo, you sill need to run "pxt bump"

**Comment by emwta** [comment]
i'm not sure how to do it properly.

**Comment by pelikhan** [comment]
In a terminal, from the repo folder, run 

   pxt bump

**Comment by emwta** [comment]
Running

![2018-05-03_023451](https://user-images.githubusercontent.com/21301794/39545179-99e2b278-4e7a-11e8-8cd8-ce152830b2bc.png)

**Comment by pelikhan** [comment]
pxt bump first pulls so make sure your local repo has merged changes from the cloud.

**Comment by emwta** [comment]
Do you have a sample of how to do it, Thank you.

**Comment by pelikhan** [comment]
git pull
pxt bump

_____________________________

**Comment by emwta** [comment]
one more time. i'm sure merged changes from the cloud.

**Comment by pelikhan** [comment]
pxt bump does create a commit - it bumps the version on PXT.json

**Comment by emwta** [comment]
i don't sure it working. 

![2018-05-03_182700](https://user-images.githubusercontent.com/21301794/39574040-e02864c8-4eff-11e8-9c43-353d136cf579.png)

**Comment by pelikhan** [comment]
Yes it worked.

_____________________________

**Comment by emwta** [comment]
Then, what to do next  step?

**Comment by pelikhan** [comment]
Make all the blocks lower case to align with coding guidelines. https://github.com/emwta/pxt-iBit/issues/1
Then bump again.
